# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3ae9ab1f5651fcdc0de024b8b4113b668d1de48b7107d287c2e48e26670e704f1d5423f22af5facc22131998465d8e3eceb1a01e9cec1d38e866a8471cb2801

test:
  secret_key_base: 7e94605397a827f209f45f7a0e97e48a1ab8c07dc405ca1c498bd90e057dc9f3bf805435ec23ed5827cc38693a12a7f9805b8024103fe7ef894b68997cacbf1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
